logo_title: Dotennin

style: white

favicon: /favicon.ico

menu:
  about: /about.html
  Github: https://github.com/dotennin

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: eirgfpXsE23neJ7WkxPUfFAW-gzGzoHsz
  appKey: sw47i3Fvb4dEyofk9S9zPgCP

highlight:
  enable: false
