logo_title: Dotennin

style: black

favicon: /favicon.ico

menu:
  作品: /project
  域名: /domain
  友联: /links
  关于: /about
  Github: https://github.com/dotennin

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: eirgfpXsE23neJ7WkxPUfFAW-gzGzoHsz
  appKey: sw47i3Fvb4dEyofk9S9zPgCP

highlight:
  enable: false
