name: Clear CDN cache
on: [push]
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only HEAD^..HEAD | grep -i 'assets/' | xargs)"
  purgeCache:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.all}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.all}}
      - name: eval purge jsdelivr cache
        run: |
          branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          for file in ${{needs.changedfiles.outputs.all}}
          do
            curl "https://purge.jsdelivr.net/gh/${{ github.repository }}@$branch_name/$file"
          done
