name: Generate m3u

on:
  # “At every 5th minute.”
  schedule:
    - cron: "*/5 * * * *" 
  # allows to manually run the job at any time
  workflow_dispatch:
  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate-m3u:
    env: 
      CI_COMMIT_MESSAGE: "bot: update m3u"
      CI_COMMIT_AUTHOR: "github-actions[bot]"
      CI_COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
    runs-on: ubuntu-22.04
    continue-on-error: true
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: output

      - name: Generate m3u
        run: |
         curl http://m3u4u.com/m3u/m/qgkjpnm22ebvmmn8ey79 > tv.m3u
         git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
         git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
         git add .
         git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
         git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

